### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by maxfriedmann** [gyllstromk/node-cloudfoundry-client#23]
Hi there,
great work!

I unfortunately have to use an endpoint that has a custom SSL Certificate installed which is available on my company laptop. The standard command line interface from Cloudfoundry accepts this certificate, with your node client I get : 

{ [Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }

Is there any way how I can work around this?

Cheers,
Max

**Comment by mpaprota** [comment]
You can disable SSL validation by:

process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

**Comment by maxfriedmann** [comment]
Perfect, that works. Many thanks!
